### ISSUE TITLE
chore: hard-code block time parameters in the codebase

### ISSUE THREAD

**Issue by NibiruHeisenberg** [NibiruChain/nibiru#1053]
See https://github.com/sei-protocol/sei-chain/blob/977c1d1b9e97ac01cf8634323d6ea77489466ada/cmd/seid/cmd/init.go#L80 for an example

**Comment by Unique-Divine** [comment]
Following some diligence with @jgimeno, the recommended settings are:
```toml
timeout_propose = "3s"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"
```
