### ISSUE TITLE
[bug] eth_getLogs should return empty instead of an error for blocks that don't exist

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/nibiru#2320]
## Status

This is still a work in progress. I'm trying to further understand why our RPC
shows this error, while it works for chains like Sonic, Arbitrum, etc.

## Context

Several DeFiLlama adapters error when using `eth_getLogs`. There's no error
description when running the adapter scripts in the DeFiLlama repo, aside from messages that say there's either a null or undefined value where there shouldn't be.

### Case 1: [DeFiLlama Adapter for Mimswap](https://github.com/DefiLlama/DefiLlama-Adapters/pull/14893)

> "The pool for Nibiru has been hardcoded for now as there's currently only one
> pool, and because getLogs doesn't work on Nibiru. I suspect it attempts to
> fetch block 1, but it doesn't exist." - https://github.com/DefiLlama/DefiLlama-Adapters/pull/14893#issue-3111289096

Error: happens in `getLogs2`

### Case 2: [DeFiLlama Adapter for Oku (Uniswap)](https://github.com/DefiLlama/DefiLlama-Adapters/pull/14890)

Remote Info:
```toml
# from `git config --edit`
[remote "nibiru"]
	url = git@github.com:NibiruChain/DefiLlama-Adapters.git
	fetch = +refs/heads/*:refs/remotes/nibiru/*
[branch "nibiru/uniswap"]
	remote = nibiru
	merge = refs/heads/nibiru/uniswap
```

You can run the adapter on this branch:
```bash
git checkout nibiru/uniswap
node test.js projects/uniswap/index.js 2>&1
```

Error:
```
Error in nibiru: [Error: Llama RPC error! method: undefined 
- host: https://evm-rpc.nibiru.fi error: Cannot read properties of null (reading 'number')
- host: https://evm-rpc.nibiru.fi error: Cannot read properties of null (reading 'number')] {
  _underlyingError: '[object Object]',
  _isCustomError: true
}
```

### Case 3: [DeFiLlama Adapter for SilverSwap](https://github.com/DefiLlama/DefiLlama-Adapters/pull/14889)

> "still can not get data from nibiru chain rpc, pls check" - https://github.com/DefiLlama/DefiLlama-Adapters/pull/14889#issuecomment-2931645776

Remote Info:
```toml
# from `git config --edit`
[remote "nibiru"]
	url = git@github.com:NibiruChain/DefiLlama-Adapters.git
	fetch = +refs/heads/*:refs/remotes/nibiru/*
[branch "nibiru/uniswap"]
	remote = nibiru
	merge = refs/heads/nibiru/uniswap
```

You can run the adapter on this branch:
```bash
git checkout nibiru/silverswap
node test.js projects/silverswap/index.js 2>&1
```

Error:
```
Error in nibiru: [Error: Llama RPC error! method: undefined 
- host: https://evm-rpc.nibiru.fi error: Cannot read properties of null (reading 'number')
- host: https://evm-rpc.nibiru.fi error: Cannot read properties of null (reading 'number')] {
  _underlyingError: '[object Object]',
  _isCustomError: true
}
```
