### ISSUE TITLE
bug(staking): Pagination does not work properly (at least in staking module)

### ISSUE THREAD

**Issue by onikonychev** [NibiruChain/nibiru#983]
How to reproduce:
I intentionally created 100+ delegations.
Now querying delegations returns
```
nibid q staking delegations-to nibivaloper1zaavvzxez0elundtn32qnk9lkm8kmcszuwx9jz --node tcp://34.130.24.87:26657 --chain-id nibiru-localnet-0
```

```
- balance:
    amount: "10"
    denom: unibi
  delegation:
    delegator_address: nibi1mkrpq4k2tlypnsnmcgnsyk3jkqlhdv3m0s2n0v
    shares: "10.000000000000000000"
    validator_address: nibivaloper1zaavvzxez0elundtn32qnk9lkm8kmcszuwx9jz
...
pagination:
  next_key: FN7IwaXVRsKtUjDiaFSt3hORaLEMFBd6xgjZE/P+TaucVAnYv7bPbeIC
  total: "0"
```

NOTICE: `total:0` looks wrong to me
If I query the next page - it returns empty result:

```
nibid q staking delegations-to nibivaloper1zaavvzxez0elundtn32qnk9lkm8kmcszuwx9jz --page-key FN7IwaXVRsKtUjDiaFSt3hORaLEMFBd6xgjZE/P+TaucVAnYv7bPbeIC --node tcp://34.130.24.87:26657 --chain-id nibiru-localnet-0
delegation_responses: []
pagination:
  next_key: null
  total: "0"
  ```
